export const ALL_BLOG_REQUEST = "ALL_PRODUCT_REQUEST";
export const ALL_BLOG_SUCCESS = "ALL_PRODUCT_SUCCESS";
export const ALL_BLOG_FAIL = "ALL_PRODUCT_FAIL";

export const BLOG_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST";
export const BLOG_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS";
export const BLOG_DETAILS_FAIL = "PRODUCT_DETAILS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
